<?php declare(strict_types = 1);

namespace Modette\ModuleInstaller\Loading;

use Composer\Composer;
use Modette\Exceptions\Logic\InvalidArgumentException;
use Modette\Exceptions\Logic\InvalidStateException;
use Modette\ModuleInstaller\Files\FileIO;
use Modette\ModuleInstaller\Package\ConfigurationValidator;
use Modette\ModuleInstaller\Package\LoaderConfiguration;
use Modette\ModuleInstaller\Package\PackageConfiguration;
use Modette\ModuleInstaller\Resolving\ModuleResolver;
use Modette\ModuleInstaller\Utils\PathResolver;
use Modette\ModuleInstaller\Utils\PluginActivator;
use Nette\PhpGenerator\ClassType;
use Nette\PhpGenerator\PhpFile;

final class LoaderGenerator
{

	/** @var Composer */
	private $composer;

	/** @var FileIO */
	private $io;

	/** @var PathResolver */
	private $pathResolver;

	/** @var ConfigurationValidator */
	private $validator;

	/** @var PackageConfiguration */
	private $rootPackageConfiguration;

	public function __construct(Composer $composer, FileIO $io, PathResolver $pathResolver, ConfigurationValidator $validator, PackageConfiguration $rootPackageConfiguration)
	{
		$this->composer = $composer;
		$this->io = $io;
		$this->pathResolver = $pathResolver;
		$this->validator = $validator;
		$this->rootPackageConfiguration = $rootPackageConfiguration;
	}

	public function generateLoader(): void
	{
		$loaderConfiguration = $this->rootPackageConfiguration->getLoader();

		if ($loaderConfiguration === null) {
			throw new InvalidStateException(sprintf(
				'Loader should be always available by this moment. Entry point should check if plugin is activated with \'%s\'',
				PluginActivator::class
			));
		}

		$resolver = new ModuleResolver(
			$this->composer,
			$this->pathResolver,
			$this->validator,
			$this->rootPackageConfiguration
		);

		$this->generateClass($loaderConfiguration, $resolver->getResolvedConfigurations());
	}

	/**
	 * @param PackageConfiguration[] $packageConfigurations
	 */
	private function generateClass(LoaderConfiguration $loaderConfiguration, array $packageConfigurations): void
	{
		$fqn = $loaderConfiguration->getClass();
		$lastSlashPosition = strrpos($fqn, '\\');

		if ($lastSlashPosition === false) {
			throw new InvalidArgumentException('Namespace of loader class must be specified.');
		}

		$schema = [];

		foreach ($packageConfigurations as $packageConfiguration) {
			$packageDirRelative = $this->pathResolver->getRelativePath($packageConfiguration->getPackage());

			foreach ($packageConfiguration->getFiles() as $fileConfiguration) {
				$schema[] = [
					'file' => $packageDirRelative . '/' . $fileConfiguration->getFile(),
					'parameters' => $fileConfiguration->getParameters(),
				];
			}
		}

		if (class_exists($fqn)) {
			if (!is_subclass_of($fqn, Loader::class)) {
				throw new InvalidStateException(sprintf(
					'\'%s\' should be instance of \'%s\'',
					$fqn,
					Loader::class
				));
			}

			$loader = new $fqn();
			assert($loader instanceof Loader);

			if ($loader->getSchema() === $schema) {
				return;
			}
		}

		$classString = substr($fqn, $lastSlashPosition + 1);
		$namespaceString = substr($fqn, 0, $lastSlashPosition);

		$file = new PhpFile();
		$file->setStrictTypes();

		$alias = $classString === 'Loader' ? 'ModuleLoader' : null;
		$namespace = $file->addNamespace($namespaceString)
			->addUse(Loader::class, $alias);

		$class = $namespace->addClass($classString)
			->setExtends(Loader::class)
			->setFinal()
			->setComment('Generated by modette/module-installer');

		$class->addProperty('schema', $schema)
			->setVisibility(ClassType::VISIBILITY_PROTECTED)
			->setComment('@var mixed[]');

		$loaderFilePath = $this->pathResolver->getRootDir() . '/' . $loaderConfiguration->getFile();
		$this->io->write($loaderFilePath, $file);
	}

}
