<?php declare(strict_types = 1);

namespace Modette\ModuleInstaller;

use Composer\Downloader\FilesystemException;
use Nette\DI\Config\Adapters\NeonAdapter;

class IO
{

	/**
	 * @return mixed[]
	 */
	public function read(string $file): array
	{
		$neon = new NeonAdapter();

		return $neon->load($file);
	}

	/**
	 * @param mixed[] $config
	 */
	public function write(string $file, array $config): void
	{
		$neon = new NeonAdapter();
		$content = $neon->dump($config);

		$content = preg_replace(
			'/^# generated by Nette/',
			'# generated by Modette',
			$content
		);

		$written = file_put_contents($file, $content);

		if ($written === false) {
			throw new FilesystemException(
				'An error occurred during writing of modules config file.'
			);
		}
	}

}
